#!/usr/bin/env python3
"""
Post-Migration SHA Verification Tool

Compares SHA-256 checksums of packages between GitLab source and GitHub destination
to detect integrity changes that may occur during cross-platform migration.

Background:
    During GH-to-GH package migrations, SHAs were observed to change after migration.
    This tool verifies whether the same issue occurs in GitLab-to-GitHub migrations.

Usage:
    # Compare using a migration report (generated by migrate_packages.py)
    python verify_sha.py --report migration_report.json \
        --gitlab-token glpat-xxx --github-token ghp_xxx --github-org my-org

    # Full scan: compare all packages in GitLab group vs GitHub org
    python verify_sha.py --full-scan --gitlab-group my-org --gitlab-token glpat-xxx \
        --github-token ghp_xxx --github-org my-org

    # Verify a specific package
    python verify_sha.py --package-name my-package --package-version 1.0.0 \
        --gitlab-project-id 123 --gitlab-token glpat-xxx \
        --github-token ghp_xxx --github-org my-org --github-repo my-repo

Environment variables:
    GITLAB_URL    - GitLab instance URL (default: https://gitlab.com)
    GITLAB_TOKEN  - GitLab PAT
    GITHUB_TOKEN  - GitHub PAT
    GITHUB_ORG    - GitHub organization
"""

import argparse
import hashlib
import json
import logging
import os
import sys
import tempfile
import time
from datetime import datetime
from pathlib import Path
from urllib.parse import quote

import requests

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

VERSION = "1.0.0"
DEFAULT_GITLAB_URL = "https://gitlab.com"
DEFAULT_GITHUB_API = "https://api.github.com"

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

_logger = logging.getLogger("sha_verification")


def setup_logging(debug=False, log_file=None):
    level = logging.DEBUG if debug else logging.INFO
    _logger.setLevel(level)
    fmt = logging.Formatter("[%(asctime)s] %(levelname)s - %(message)s", datefmt="%Y-%m-%d %H:%M:%S")

    console = logging.StreamHandler(sys.stdout)
    console.setLevel(level)
    console.setFormatter(fmt)
    _logger.addHandler(console)

    if log_file:
        fh = logging.FileHandler(log_file, mode="w", encoding="utf-8")
        fh.setLevel(logging.DEBUG)
        fh.setFormatter(fmt)
        _logger.addHandler(fh)


def log(msg):
    _logger.info(msg)


def debug_log(msg):
    _logger.debug(msg)


def error_log(msg):
    _logger.error(msg)


# ---------------------------------------------------------------------------
# .env autoload
# ---------------------------------------------------------------------------

def _load_dotenv():
    try:
        from dotenv import load_dotenv, find_dotenv
        env_file = find_dotenv(usecwd=True)
        if env_file:
            load_dotenv(env_file, override=False)
    except ImportError:
        pass


_load_dotenv()


# ---------------------------------------------------------------------------
# SHA Utility
# ---------------------------------------------------------------------------

def compute_sha256(file_path):
    """Compute SHA-256 hash of a file."""
    sha256 = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            sha256.update(chunk)
    return sha256.hexdigest()


def compute_sha256_bytes(data: bytes) -> str:
    """Compute SHA-256 from raw bytes."""
    return hashlib.sha256(data).hexdigest()


# ---------------------------------------------------------------------------
# GitLab Package Fetcher
# ---------------------------------------------------------------------------

class GitLabFetcher:
    """Fetch package files and their SHAs from GitLab."""

    def __init__(self, gitlab_url, token, timeout=60, retries=3):
        self.base_url = gitlab_url.rstrip("/") + "/api/v4"
        self.session = requests.Session()
        self.session.headers.update({"PRIVATE-TOKEN": token})
        self.timeout = timeout
        self.retries = retries

    def _get(self, path, params=None, stream=False):
        url = self.base_url + path
        for attempt in range(self.retries + 1):
            try:
                resp = self.session.get(url, params=params, timeout=self.timeout, stream=stream)
                if resp.status_code == 429:
                    time.sleep(int(resp.headers.get("Retry-After", 2 ** (attempt + 1))))
                    continue
                if resp.status_code >= 500 and attempt < self.retries:
                    time.sleep(2 ** attempt)
                    continue
                return resp
            except (requests.exceptions.ConnectionError, requests.exceptions.Timeout):
                if attempt >= self.retries:
                    raise
                time.sleep(2 ** attempt)
        return resp

    def _get_paginated(self, path, params=None):
        results = []
        page = 1
        base_params = dict(params or {})
        while True:
            base_params["per_page"] = 100
            base_params["page"] = page
            resp = self._get(path, params=base_params)
            if resp.status_code == 404:
                return results
            resp.raise_for_status()
            items = resp.json()
            if not items:
                break
            results.extend(items)
            next_page = resp.headers.get("X-Next-Page")
            if not next_page:
                break
            page = int(next_page)
        return results

    def get_group_projects(self, group_path):
        encoded = quote(group_path, safe="")
        return self._get_paginated(
            f"/groups/{encoded}/projects",
            params={"include_subgroups": "true", "with_shared": "false"},
        )

    def get_project_packages(self, project_id):
        return self._get_paginated(f"/projects/{project_id}/packages")

    def get_package_files(self, project_id, package_id):
        resp = self._get(f"/projects/{project_id}/packages/{package_id}/package_files")
        if resp.status_code == 404:
            return []
        resp.raise_for_status()
        return resp.json()

    def download_file(self, project_id, package_id, file_id, dest_path):
        """Download a package file and return its SHA-256."""
        path = f"/projects/{project_id}/packages/{package_id}/package_files/{file_id}/download"
        resp = self._get(path, stream=True)
        if resp.status_code != 200:
            return None

        Path(dest_path).parent.mkdir(parents=True, exist_ok=True)
        with open(dest_path, "wb") as f:
            for chunk in resp.iter_content(chunk_size=8192):
                f.write(chunk)
        return compute_sha256(dest_path)


# ---------------------------------------------------------------------------
# GitHub Package Fetcher
# ---------------------------------------------------------------------------

class GitHubFetcher:
    """Fetch package files and their SHAs from GitHub."""

    def __init__(self, github_token, github_org, timeout=60, retries=3):
        self.token = github_token
        self.org = github_org
        self.session = requests.Session()
        self.session.headers.update({
            "Authorization": f"Bearer {github_token}",
            "Accept": "application/vnd.github.v3+json",
        })
        self.timeout = timeout
        self.retries = retries

    def _get(self, url, params=None, stream=False):
        for attempt in range(self.retries + 1):
            try:
                resp = self.session.get(url, params=params, timeout=self.timeout, stream=stream)
                if resp.status_code == 429:
                    time.sleep(int(resp.headers.get("Retry-After", 2 ** (attempt + 1))))
                    continue
                if resp.status_code >= 500 and attempt < self.retries:
                    time.sleep(2 ** attempt)
                    continue
                return resp
            except (requests.exceptions.ConnectionError, requests.exceptions.Timeout):
                if attempt >= self.retries:
                    raise
                time.sleep(2 ** attempt)
        return resp

    def get_org_packages(self, package_type="npm"):
        """List all packages in the org of a given type."""
        url = f"{DEFAULT_GITHUB_API}/orgs/{self.org}/packages?package_type={package_type}"
        resp = self._get(url)
        if resp.status_code != 200:
            return []
        return resp.json()

    def get_package_versions(self, package_type, package_name):
        """Get all versions of a package."""
        encoded_name = quote(package_name, safe="")
        url = f"{DEFAULT_GITHUB_API}/orgs/{self.org}/packages/{package_type}/{encoded_name}/versions"
        resp = self._get(url)
        if resp.status_code != 200:
            return []
        return resp.json()

    def get_release_assets(self, repo_name, tag_name):
        """Get release assets for generic package verification."""
        url = f"{DEFAULT_GITHUB_API}/repos/{self.org}/{repo_name}/releases/tags/{tag_name}"
        resp = self._get(url)
        if resp.status_code != 200:
            return []
        release = resp.json()
        return release.get("assets", [])

    def download_release_asset(self, asset_url, dest_path):
        """Download a release asset and return its SHA-256."""
        headers = {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/octet-stream",
        }
        resp = requests.get(asset_url, headers=headers, timeout=self.timeout, stream=True)
        if resp.status_code != 200:
            return None

        Path(dest_path).parent.mkdir(parents=True, exist_ok=True)
        with open(dest_path, "wb") as f:
            for chunk in resp.iter_content(chunk_size=8192):
                f.write(chunk)
        return compute_sha256(dest_path)


# ---------------------------------------------------------------------------
# Verification Engine
# ---------------------------------------------------------------------------

class SHAVerificationEngine:
    """Compares SHA-256 checksums between GitLab source and GitHub destination."""

    def __init__(self, gitlab_fetcher, github_fetcher, work_dir):
        self.gitlab = gitlab_fetcher
        self.github = github_fetcher
        self.work_dir = Path(work_dir)
        self.work_dir.mkdir(parents=True, exist_ok=True)

        self.results = {
            "verification_started": datetime.utcnow().isoformat(),
            "total_files_checked": 0,
            "sha_matches": 0,
            "sha_mismatches": 0,
            "files_not_found_on_github": 0,
            "files_not_found_on_gitlab": 0,
            "errors": 0,
            "mismatches": [],
            "details": [],
        }

    def verify_from_report(self, report_path):
        """Verify SHAs using a migration report generated by migrate_packages.py."""
        log(f"Loading migration report: {report_path}")

        with open(report_path, "r", encoding="utf-8") as f:
            report = json.load(f)

        details = report.get("details", [])
        if not details:
            log("No package details found in report.")
            return

        log(f"Found {len(details)} package(s) to verify")

        for pkg_detail in details:
            pkg_name = pkg_detail["package_name"]
            pkg_type = pkg_detail["package_type"]
            version = pkg_detail["version"]
            github_repo = pkg_detail["github_repo"]
            files = pkg_detail.get("files", [])

            log(f"\nVerifying: {pkg_name}@{version} ({pkg_type})")

            for file_info in files:
                file_name = file_info["name"]
                source_sha = file_info["sha256"]

                self.results["total_files_checked"] += 1

                # Get SHA from GitHub
                github_sha = self._get_github_file_sha(
                    pkg_name, pkg_type, version, file_name, github_repo
                )

                if github_sha is None:
                    log(f"  {file_name}: NOT FOUND on GitHub")
                    self.results["files_not_found_on_github"] += 1
                    self.results["details"].append({
                        "file": file_name,
                        "package": f"{pkg_name}@{version}",
                        "status": "not_found_on_github",
                        "source_sha256": source_sha,
                    })
                elif github_sha == source_sha:
                    log(f"  {file_name}: MATCH ({source_sha[:16]}...)")
                    self.results["sha_matches"] += 1
                    self.results["details"].append({
                        "file": file_name,
                        "package": f"{pkg_name}@{version}",
                        "status": "match",
                        "sha256": source_sha,
                    })
                else:
                    log(f"  {file_name}: MISMATCH!")
                    log(f"    GitLab SHA: {source_sha}")
                    log(f"    GitHub SHA: {github_sha}")
                    self.results["sha_mismatches"] += 1
                    mismatch = {
                        "file": file_name,
                        "package": f"{pkg_name}@{version}",
                        "package_type": pkg_type,
                        "status": "mismatch",
                        "gitlab_sha256": source_sha,
                        "github_sha256": github_sha,
                        "github_repo": github_repo,
                    }
                    self.results["mismatches"].append(mismatch)
                    self.results["details"].append(mismatch)

        self._finalize()

    def verify_full_scan(self, gitlab_group):
        """
        Full scan: download packages from both GitLab and GitHub,
        compute SHAs, and compare.
        """
        log(f"Starting full SHA verification scan for group: {gitlab_group}")

        projects = self.gitlab.get_group_projects(gitlab_group)
        log(f"Found {len(projects)} projects")

        for project in projects:
            project_id = project["id"]
            project_path = project.get("path_with_namespace", "")
            project_name = project.get("path", project.get("name", ""))

            packages = self.gitlab.get_project_packages(project_id)
            if not packages:
                continue

            log(f"\nProject: {project_path} ({len(packages)} packages)")

            for pkg in packages:
                pkg_id = pkg["id"]
                pkg_name = pkg.get("name", "")
                pkg_type = pkg.get("package_type", "generic")
                pkg_version = pkg.get("version", "")

                log(f"  [{pkg_type}] {pkg_name}@{pkg_version}")

                pkg_files = self.gitlab.get_package_files(project_id, pkg_id)
                if not pkg_files:
                    continue

                for pf in pkg_files:
                    file_id = pf.get("id")
                    file_name = pf.get("file_name", "")
                    gitlab_reported_sha = pf.get("file_sha256", "")

                    self.results["total_files_checked"] += 1

                    # Download from GitLab
                    gl_dest = self.work_dir / "gitlab" / str(project_id) / str(pkg_id) / file_name
                    gitlab_sha = self.gitlab.download_file(
                        project_id, pkg_id, file_id, str(gl_dest)
                    )

                    if not gitlab_sha:
                        error_log(f"    Could not download {file_name} from GitLab")
                        self.results["files_not_found_on_gitlab"] += 1
                        continue

                    # Verify GitLab reported SHA vs computed
                    if gitlab_reported_sha and gitlab_sha != gitlab_reported_sha:
                        log(f"    WARNING: GitLab API SHA != downloaded SHA for {file_name}")

                    # Get SHA from GitHub
                    github_sha = self._get_github_file_sha(
                        pkg_name, pkg_type, pkg_version, file_name, project_name
                    )

                    if github_sha is None:
                        log(f"    {file_name}: NOT FOUND on GitHub")
                        self.results["files_not_found_on_github"] += 1
                        self.results["details"].append({
                            "file": file_name,
                            "package": f"{pkg_name}@{pkg_version}",
                            "project": project_path,
                            "status": "not_found_on_github",
                            "gitlab_sha256": gitlab_sha,
                        })
                    elif github_sha == gitlab_sha:
                        log(f"    {file_name}: MATCH")
                        self.results["sha_matches"] += 1
                    else:
                        log(f"    {file_name}: SHA MISMATCH!")
                        log(f"      GitLab: {gitlab_sha}")
                        log(f"      GitHub: {github_sha}")
                        self.results["sha_mismatches"] += 1
                        mismatch = {
                            "file": file_name,
                            "package": f"{pkg_name}@{pkg_version}",
                            "package_type": pkg_type,
                            "project": project_path,
                            "status": "mismatch",
                            "gitlab_sha256": gitlab_sha,
                            "github_sha256": github_sha,
                        }
                        self.results["mismatches"].append(mismatch)
                        self.results["details"].append(mismatch)

        self._finalize()

    def verify_single_package(self, project_id, pkg_name, pkg_version, github_repo):
        """Verify a single specific package."""
        log(f"Verifying single package: {pkg_name}@{pkg_version}")

        packages = self.gitlab.get_project_packages(project_id)
        target_pkg = None
        for pkg in packages:
            if pkg.get("name") == pkg_name and pkg.get("version") == pkg_version:
                target_pkg = pkg
                break

        if not target_pkg:
            error_log(f"Package {pkg_name}@{pkg_version} not found in project {project_id}")
            return

        pkg_id = target_pkg["id"]
        pkg_type = target_pkg.get("package_type", "generic")
        pkg_files = self.gitlab.get_package_files(project_id, pkg_id)

        if not pkg_files:
            log("No files found for this package")
            return

        log(f"Found {len(pkg_files)} file(s) to verify")

        for pf in pkg_files:
            file_id = pf.get("id")
            file_name = pf.get("file_name", "")

            self.results["total_files_checked"] += 1

            # Download from GitLab
            gl_dest = self.work_dir / "gitlab" / file_name
            gitlab_sha = self.gitlab.download_file(project_id, pkg_id, file_id, str(gl_dest))

            if not gitlab_sha:
                error_log(f"  Could not download {file_name} from GitLab")
                self.results["errors"] += 1
                continue

            # Get from GitHub
            github_sha = self._get_github_file_sha(
                pkg_name, pkg_type, pkg_version, file_name, github_repo
            )

            if github_sha is None:
                log(f"  {file_name}: NOT FOUND on GitHub")
                self.results["files_not_found_on_github"] += 1
            elif github_sha == gitlab_sha:
                log(f"  {file_name}: SHA MATCH ({gitlab_sha[:16]}...)")
                self.results["sha_matches"] += 1
            else:
                log(f"  {file_name}: SHA MISMATCH!")
                log(f"    GitLab: {gitlab_sha}")
                log(f"    GitHub: {github_sha}")
                self.results["sha_mismatches"] += 1
                self.results["mismatches"].append({
                    "file": file_name,
                    "package": f"{pkg_name}@{pkg_version}",
                    "package_type": pkg_type,
                    "gitlab_sha256": gitlab_sha,
                    "github_sha256": github_sha,
                    "github_repo": github_repo,
                })

        self._finalize()

    def _get_github_file_sha(self, pkg_name, pkg_type, version, file_name, github_repo):
        """
        Attempt to get the SHA-256 of a file on GitHub Packages.
        For generic packages (stored as release assets), downloads and computes.
        """
        if pkg_type == "generic":
            # Generic packages are stored as release assets
            tag_name = f"{pkg_name}-v{version}"
            assets = self.github.get_release_assets(github_repo, tag_name)
            for asset in assets:
                if asset.get("name") == file_name:
                    # Download and compute SHA
                    dest = self.work_dir / "github" / github_repo / tag_name / file_name
                    sha = self.github.download_release_asset(asset["url"], str(dest))
                    return sha
            return None

        elif pkg_type in ("npm", "maven", "nuget"):
            # For registry packages, we need to download from GitHub's package registry
            # This is more complex and depends on the package type
            # For npm: download tarball from npm.pkg.github.com
            # For maven: download artifact from maven.pkg.github.com
            # For nuget: download from nuget.pkg.github.com

            if pkg_type == "npm":
                return self._get_npm_sha(pkg_name, version)
            elif pkg_type == "maven":
                return self._get_maven_sha(pkg_name, version, file_name, github_repo)
            elif pkg_type == "nuget":
                return self._get_nuget_sha(pkg_name, version, file_name)

        return None

    def _get_npm_sha(self, pkg_name, version):
        """Download npm package from GitHub and compute SHA."""
        scoped_name = f"@{self.github.org}/{pkg_name}"
        url = f"https://npm.pkg.github.com/{quote(scoped_name, safe='@/')}"
        resp = self.github._get(url)
        if resp.status_code != 200:
            return None

        pkg_info = resp.json()
        versions = pkg_info.get("versions", {})
        ver_info = versions.get(version, {})
        tarball_url = ver_info.get("dist", {}).get("tarball")

        if not tarball_url:
            return None

        dest = self.work_dir / "github" / "npm" / f"{pkg_name}-{version}.tgz"
        dest.parent.mkdir(parents=True, exist_ok=True)

        headers = {"Authorization": f"Bearer {self.github.token}"}
        resp = requests.get(tarball_url, headers=headers, timeout=60, stream=True)
        if resp.status_code != 200:
            return None

        with open(dest, "wb") as f:
            for chunk in resp.iter_content(chunk_size=8192):
                f.write(chunk)
        return compute_sha256(str(dest))

    def _get_maven_sha(self, pkg_name, version, file_name, github_repo):
        """Download Maven artifact from GitHub and compute SHA."""
        parts = pkg_name.rsplit(".", 1)
        group_id = parts[0] if len(parts) > 1 else self.github.org
        artifact_id = parts[-1]
        group_path = group_id.replace(".", "/")

        url = (
            f"https://maven.pkg.github.com/{self.github.org}/{github_repo}"
            f"/{group_path}/{artifact_id}/{version}/{file_name}"
        )

        dest = self.work_dir / "github" / "maven" / file_name
        dest.parent.mkdir(parents=True, exist_ok=True)

        headers = {"Authorization": f"Bearer {self.github.token}"}
        resp = requests.get(url, headers=headers, timeout=60, stream=True)
        if resp.status_code != 200:
            return None

        with open(dest, "wb") as f:
            for chunk in resp.iter_content(chunk_size=8192):
                f.write(chunk)
        return compute_sha256(str(dest))

    def _get_nuget_sha(self, pkg_name, version, file_name):
        """Download NuGet package from GitHub and compute SHA."""
        url = (
            f"https://nuget.pkg.github.com/{self.github.org}"
            f"/download/{pkg_name}/{version}/{pkg_name}.{version}.nupkg"
        )

        dest = self.work_dir / "github" / "nuget" / f"{pkg_name}.{version}.nupkg"
        dest.parent.mkdir(parents=True, exist_ok=True)

        headers = {"Authorization": f"Bearer {self.github.token}"}
        resp = requests.get(url, headers=headers, timeout=60, stream=True)
        if resp.status_code != 200:
            return None

        with open(dest, "wb") as f:
            for chunk in resp.iter_content(chunk_size=8192):
                f.write(chunk)
        return compute_sha256(str(dest))

    def _finalize(self):
        """Save results and print summary."""
        self.results["verification_completed"] = datetime.utcnow().isoformat()

        # Save report
        report_path = self.work_dir / "sha_verification_report.json"
        with open(report_path, "w", encoding="utf-8") as f:
            json.dump(self.results, f, indent=2, default=str)
        log(f"\nVerification report saved to: {report_path}")

        # Print summary
        r = self.results
        log("\n" + "=" * 60)
        log("SHA VERIFICATION SUMMARY")
        log("=" * 60)
        log(f"  Total files checked:        {r['total_files_checked']}")
        log(f"  SHA matches (identical):    {r['sha_matches']}")
        log(f"  SHA mismatches (CHANGED):   {r['sha_mismatches']}")
        log(f"  Not found on GitHub:        {r['files_not_found_on_github']}")
        log(f"  Not found on GitLab:        {r['files_not_found_on_gitlab']}")
        log(f"  Errors:                     {r['errors']}")

        if r["mismatches"]:
            log("\n  MISMATCH DETAILS (SHAs changed during migration):")
            log("  " + "-" * 56)
            for m in r["mismatches"]:
                log(f"  Package: {m['package']}")
                log(f"  File:    {m['file']}")
                log(f"  Type:    {m.get('package_type', 'unknown')}")
                log(f"  GitLab:  {m['gitlab_sha256']}")
                log(f"  GitHub:  {m['github_sha256']}")
                log(f"  " + "-" * 56)

            log("\n  CONCLUSION: SHA changes detected! Similar to GH-GH migration issue.")
            log("  Investigate whether GitHub re-processes/re-packages files on upload.")
        else:
            log("\n  CONCLUSION: All SHAs match. No integrity changes detected.")

        log("=" * 60)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args():
    parser = argparse.ArgumentParser(
        description="Verify SHA-256 integrity of packages migrated from GitLab to GitHub"
    )

    # Source (GitLab)
    parser.add_argument("--gitlab-url", default=os.getenv("GITLAB_URL", DEFAULT_GITLAB_URL))
    parser.add_argument("--gitlab-token", default=os.getenv("GITLAB_TOKEN"))
    parser.add_argument("--gitlab-group", default=None, help="GitLab group for full scan")
    parser.add_argument("--gitlab-project-id", type=int, default=None,
                        help="GitLab project ID for single package verification")

    # Destination (GitHub)
    parser.add_argument("--github-token", default=os.getenv("GITHUB_TOKEN"))
    parser.add_argument("--github-org", default=os.getenv("GITHUB_ORG"))
    parser.add_argument("--github-repo", default=None,
                        help="GitHub repo name for single package verification")

    # Modes
    parser.add_argument("--report", default=None,
                        help="Path to migration_report.json from migrate_packages.py")
    parser.add_argument("--full-scan", action="store_true",
                        help="Full scan: compare all packages in GitLab group vs GitHub")
    parser.add_argument("--package-name", default=None,
                        help="Specific package name to verify")
    parser.add_argument("--package-version", default=None,
                        help="Specific package version to verify")

    # Options
    parser.add_argument("--work-dir", default=None, help="Working directory for downloads")
    parser.add_argument("--debug", action="store_true")
    parser.add_argument("--log-file", default="sha_verification.log")

    return parser.parse_args()


def main():
    args = parse_args()
    setup_logging(debug=args.debug, log_file=args.log_file)

    log(f"SHA Verification Tool v{VERSION}")

    # Validate
    if not args.gitlab_token:
        error_log("GitLab token required (--gitlab-token or GITLAB_TOKEN)")
        sys.exit(1)
    if not args.github_token:
        error_log("GitHub token required (--github-token or GITHUB_TOKEN)")
        sys.exit(1)
    if not args.github_org:
        error_log("GitHub org required (--github-org or GITHUB_ORG)")
        sys.exit(1)

    # Determine mode
    if not args.report and not args.full_scan and not args.package_name:
        error_log("Specify one of: --report, --full-scan, or --package-name + --package-version")
        sys.exit(1)

    # Working directory
    work_dir = args.work_dir or tempfile.mkdtemp(prefix="sha_verify_")
    log(f"Working directory: {work_dir}")

    # Initialize fetchers
    gitlab_fetcher = GitLabFetcher(args.gitlab_url, args.gitlab_token)
    github_fetcher = GitHubFetcher(args.github_token, args.github_org)

    engine = SHAVerificationEngine(gitlab_fetcher, github_fetcher, work_dir)

    if args.report:
        engine.verify_from_report(args.report)
    elif args.full_scan:
        if not args.gitlab_group:
            error_log("--gitlab-group is required for full scan")
            sys.exit(1)
        engine.verify_full_scan(args.gitlab_group)
    elif args.package_name:
        if not args.gitlab_project_id:
            error_log("--gitlab-project-id is required for single package verification")
            sys.exit(1)
        if not args.package_version:
            error_log("--package-version is required for single package verification")
            sys.exit(1)
        if not args.github_repo:
            error_log("--github-repo is required for single package verification")
            sys.exit(1)
        engine.verify_single_package(
            args.gitlab_project_id, args.package_name,
            args.package_version, args.github_repo,
        )


if __name__ == "__main__":
    main()
