#!/usr/bin/env python3
"""
GitLab-to-GitHub Permission Migration Execution Tool
=====================================================

Reads mapping CSV files (generated by users_permissions_inventory.py) and
the inventory Excel workbook, then creates GitHub teams, invites users,
and sets repository permissions via the GitHub REST API.

Prerequisites:
  1. Run users_permissions_inventory.py first to generate:
     - GitLab_UsersPermissions_Inventory.xlsx
     - gitlab_to_github_user_mapping.csv
     - gitlab_to_github_group_mapping.csv
     - gitlab_to_github_project_mapping.csv
  2. Fill in the GitHub columns in the mapping CSVs
  3. Create a GitHub PAT with: admin:org, repo, read:user scopes

Usage:
    python migrate_permissions.py --github-org my-org --github-token ghp_xxx --mappings-dir .
    python migrate_permissions.py --github-org my-org --github-token ghp_xxx --mappings-dir . --dry-run
    python migrate_permissions.py --github-org my-org --github-token ghp_xxx --mappings-dir . --skip-teams --skip-repos

Environment variables (CLI overrides take precedence):
    GITHUB_TOKEN - GitHub Personal Access Token
    GITHUB_ORG   - GitHub organization name
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import os
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import requests

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

VERSION = "1.1.0"
DEFAULT_LOG_FILENAME = "migrate_permissions.log"
GITHUB_API_BASE = "https://api.github.com"
MAX_RETRIES = 3
BACKOFF_BASE = 1.0

# GitHub team permission levels for repositories
GITHUB_REPO_PERMISSIONS = ["pull", "triage", "push", "maintain", "admin"]

# Map our role names to GitHub API permission values
ROLE_TO_REPO_PERMISSION: dict[str, str] = {
    "Read": "pull",
    "Triage": "triage",
    "Write": "push",
    "Maintain": "maintain",
    "Admin": "admin",
}

# Map our role names to GitHub team membership roles
ROLE_TO_TEAM_ROLE: dict[str, str] = {
    "Read": "member",
    "Triage": "member",
    "Write": "member",
    "Maintain": "maintainer",
    "Admin": "maintainer",
}

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

log = logging.getLogger("migrate_permissions")


def setup_logging(log_file: Path, debug: bool = False) -> None:
    level = logging.DEBUG if debug else logging.INFO
    fmt = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    handlers: list[logging.Handler] = [
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(str(log_file), mode="w", encoding="utf-8"),
    ]
    logging.basicConfig(level=level, format=fmt, handlers=handlers)


# ---------------------------------------------------------------------------
# GitHub API Client
# ---------------------------------------------------------------------------

class GitHubClient:
    """HTTP client for the GitHub REST API with retry logic."""

    def __init__(self, token: str, dry_run: bool = False):
        self.token = token
        self.dry_run = dry_run
        self._session = requests.Session()
        self._session.headers.update({
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        })

    def _request(self, method: str, endpoint: str, **kwargs: Any) -> requests.Response | None:
        """Make a request with retry logic."""
        url = f"{GITHUB_API_BASE}/{endpoint.lstrip('/')}"

        if self.dry_run and method != "GET":
            log.info("[DRY-RUN] %s %s %s", method, url, kwargs.get("json", ""))
            return None

        # Allow per-request header overrides
        extra_headers = kwargs.pop("headers", None)

        for attempt in range(1, MAX_RETRIES + 1):
            try:
                req_kwargs = dict(**kwargs)
                if extra_headers:
                    req_kwargs["headers"] = extra_headers
                resp = self._session.request(method, url, timeout=30, **req_kwargs)

                # Rate limit handling
                if resp.status_code == 403 and "rate limit" in resp.text.lower():
                    reset = resp.headers.get("X-RateLimit-Reset", "")
                    wait = max(float(reset) - time.time(), 1.0) if reset else 60.0
                    log.warning("Rate limited, sleeping %.0fs", wait)
                    time.sleep(wait)
                    continue

                if resp.status_code == 429:
                    retry_after = float(resp.headers.get("Retry-After", "60"))
                    log.warning("429 rate limited, sleeping %.0fs", retry_after)
                    time.sleep(retry_after)
                    continue

                if resp.status_code >= 500:
                    backoff = BACKOFF_BASE * (2 ** (attempt - 1))
                    log.warning("Server error %d, retrying in %.1fs", resp.status_code, backoff)
                    time.sleep(backoff)
                    continue

                return resp
            except (requests.exceptions.Timeout, requests.exceptions.ConnectionError) as e:
                backoff = BACKOFF_BASE * (2 ** (attempt - 1))
                log.warning("Request error: %s, retrying in %.1fs", e, backoff)
                time.sleep(backoff)

        log.error("Failed after %d retries: %s %s", MAX_RETRIES, method, url)
        return None

    def get(self, endpoint: str, **kwargs: Any) -> requests.Response | None:
        return self._request("GET", endpoint, **kwargs)

    def post(self, endpoint: str, **kwargs: Any) -> requests.Response | None:
        return self._request("POST", endpoint, **kwargs)

    def put(self, endpoint: str, **kwargs: Any) -> requests.Response | None:
        return self._request("PUT", endpoint, **kwargs)

    def patch(self, endpoint: str, **kwargs: Any) -> requests.Response | None:
        return self._request("PATCH", endpoint, **kwargs)


# ---------------------------------------------------------------------------
# Data loading from mapping CSVs
# ---------------------------------------------------------------------------

@dataclass
class UserMapping:
    gitlab_user_id: int
    gitlab_username: str
    name: str
    email: str
    github_username: str


@dataclass
class GroupMapping:
    gitlab_group_id: int
    gitlab_group_path: str
    depth: int
    parent_group_path: str
    github_org: str
    github_team_slug: str
    github_team_parent: str


@dataclass
class ProjectMapping:
    gitlab_project_id: int
    gitlab_project_path: str
    visibility: str
    github_org: str
    github_repo_name: str
    github_visibility: str


def load_user_mapping(path: Path) -> dict[str, UserMapping]:
    """Load user mapping CSV. Key: gitlab_username."""
    mappings: dict[str, UserMapping] = {}
    if not path.exists():
        log.warning("User mapping file not found: %s", path)
        return mappings
    with open(path, encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            gh_user = row.get("github_username", "").strip()
            if not gh_user:
                continue  # Skip unmapped users
            mappings[row["gitlab_username"]] = UserMapping(
                gitlab_user_id=int(row.get("gitlab_user_id", 0)),
                gitlab_username=row["gitlab_username"],
                name=row.get("name", ""),
                email=row.get("email", ""),
                github_username=gh_user,
            )
    log.info("Loaded %d user mappings (skipped unmapped)", len(mappings))
    return mappings


def load_group_mapping(path: Path) -> dict[str, GroupMapping]:
    """Load group mapping CSV. Key: gitlab_group_path."""
    mappings: dict[str, GroupMapping] = {}
    if not path.exists():
        log.warning("Group mapping file not found: %s", path)
        return mappings
    with open(path, encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            slug = row.get("github_team_slug", "").strip()
            if not slug:
                continue  # Skip unmapped groups
            mappings[row["gitlab_group_path"]] = GroupMapping(
                gitlab_group_id=int(row.get("gitlab_group_id", 0)),
                gitlab_group_path=row["gitlab_group_path"],
                depth=int(row.get("depth", 0)),
                parent_group_path=row.get("parent_group_path", ""),
                github_org=row.get("github_org", "").strip(),
                github_team_slug=slug,
                github_team_parent=row.get("github_team_parent", "").strip(),
            )
    log.info("Loaded %d group mappings (skipped unmapped)", len(mappings))
    return mappings


def load_project_mapping(path: Path) -> dict[str, ProjectMapping]:
    """Load project mapping CSV. Key: gitlab_project_path."""
    mappings: dict[str, ProjectMapping] = {}
    if not path.exists():
        log.warning("Project mapping file not found: %s", path)
        return mappings
    with open(path, encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            repo = row.get("github_repo_name", "").strip()
            if not repo:
                continue
            mappings[row["gitlab_project_path"]] = ProjectMapping(
                gitlab_project_id=int(row.get("gitlab_project_id", 0)),
                gitlab_project_path=row["gitlab_project_path"],
                visibility=row.get("visibility", "private"),
                github_org=row.get("github_org", "").strip(),
                github_repo_name=repo,
                github_visibility=row.get("github_visibility", "private"),
            )
    log.info("Loaded %d project mappings (skipped unmapped)", len(mappings))
    return mappings


# ---------------------------------------------------------------------------
# Load effective permissions from Excel
# ---------------------------------------------------------------------------

def load_effective_permissions(excel_path: Path) -> tuple[list[dict], list[dict]]:
    """Load effective group and project permissions from the inventory Excel."""
    try:
        import openpyxl
    except ImportError:
        log.error("openpyxl is required: pip install openpyxl")
        sys.exit(1)

    if not excel_path.exists():
        log.error("Inventory Excel not found: %s", excel_path)
        sys.exit(1)

    wb = openpyxl.load_workbook(str(excel_path), read_only=True)

    def read_sheet(name: str) -> list[dict]:
        if name not in wb.sheetnames:
            log.warning("Sheet '%s' not found in workbook", name)
            return []
        ws = wb[name]
        rows = list(ws.iter_rows(values_only=True))
        if not rows:
            return []
        headers = [str(h) for h in rows[0]]
        return [dict(zip(headers, row)) for row in rows[1:]]

    group_perms = read_sheet("EffectiveGroupPermissions")
    project_perms = read_sheet("EffectiveProjectPermissions")
    wb.close()

    log.info("Loaded %d effective group perms, %d effective project perms from Excel",
             len(group_perms), len(project_perms))
    return group_perms, project_perms


# ---------------------------------------------------------------------------
# Migration execution
# ---------------------------------------------------------------------------

class PermissionMigrator:
    """Executes the GitHub permission migration."""

    def __init__(self, client: GitHubClient, org: str,
                 user_map: dict[str, UserMapping],
                 group_map: dict[str, GroupMapping],
                 project_map: dict[str, ProjectMapping],
                 group_perms: list[dict],
                 project_perms: list[dict]):
        self.client = client
        self.org = org
        self.user_map = user_map
        self.group_map = group_map
        self.project_map = project_map
        self.group_perms = group_perms
        self.project_perms = project_perms

        # Tracking
        self.teams_created: list[str] = []
        self.teams_updated: list[str] = []
        self.teams_skipped: list[str] = []
        self.org_members_existing: list[str] = []
        self.org_members_invited: list[str] = []
        self.org_members_failed: list[str] = []
        self.members_added: list[str] = []
        self.members_updated: list[str] = []
        self.members_skipped: list[str] = []
        self.members_failed: list[str] = []
        self.repo_perms_set: list[str] = []
        self.repo_perms_updated: list[str] = []
        self.repo_perms_skipped: list[str] = []
        self.repo_perms_failed: list[str] = []

    # ------------------------------------------------------------------
    # Org membership (pre-check)
    # ------------------------------------------------------------------

    def ensure_org_membership(self) -> None:
        """Ensure all mapped users are org members. Invite if not."""
        log.info("Checking org membership for %d mapped users in '%s'...",
                 len(self.user_map), self.org)

        for um in self.user_map.values():
            gh_user = um.github_username

            # Check current membership status
            resp = self.client.get(f"orgs/{self.org}/members/{gh_user}")
            if resp and resp.status_code == 204:
                # 204 = user is an active member
                log.debug("User '%s' is already an org member, skipping", gh_user)
                self.org_members_existing.append(gh_user)
                continue

            # Check if there's a pending invitation already
            resp_pending = self.client.get(
                f"orgs/{self.org}/invitations",
                params={"per_page": 100},
            )
            already_invited = False
            if resp_pending and resp_pending.status_code == 200:
                for inv in resp_pending.json():
                    if inv.get("login", "").lower() == gh_user.lower():
                        log.debug("User '%s' already has pending invitation, skipping", gh_user)
                        self.org_members_existing.append(f"{gh_user} (pending)")
                        already_invited = True
                        break
            if already_invited:
                continue

            # Add user to org via memberships API (invites if not already a member)
            invite_resp = self.client.put(
                f"orgs/{self.org}/memberships/{gh_user}",
                json={"role": "member"},
            )
            if invite_resp is None and self.client.dry_run:
                self.org_members_invited.append(gh_user)
            elif invite_resp and invite_resp.status_code in (200, 201):
                state = invite_resp.json().get("state", "unknown")
                if state == "active":
                    log.info("User '%s' added to org (already had account)", gh_user)
                else:
                    log.info("User '%s' invited to org (state: %s)", gh_user, state)
                self.org_members_invited.append(f"{gh_user} ({state})")
            else:
                status = invite_resp.status_code if invite_resp else "N/A"
                body = invite_resp.text[:200] if invite_resp else ""
                log.warning("Failed to invite '%s' to org: %s %s", gh_user, status, body)
                self.org_members_failed.append(gh_user)

        log.info("Org membership — existing: %d, invited: %d, failed: %d",
                 len(self.org_members_existing), len(self.org_members_invited),
                 len(self.org_members_failed))

    # ------------------------------------------------------------------
    # Teams
    # ------------------------------------------------------------------

    def create_teams(self) -> None:
        """Create GitHub teams from group mapping."""
        log.info("Creating GitHub teams in org '%s'...", self.org)

        # Sort by depth so parents are created before children
        sorted_groups = sorted(self.group_map.values(), key=lambda g: g.depth)

        for gm in sorted_groups:
            org = gm.github_org or self.org
            slug = gm.github_team_slug

            # Resolve desired parent team ID
            desired_parent_id: int | None = None
            if gm.github_team_parent:
                parent_resp = self.client.get(f"orgs/{org}/teams/{gm.github_team_parent}")
                if parent_resp and parent_resp.status_code == 200:
                    desired_parent_id = parent_resp.json()["id"]

            # Check if team already exists
            resp = self.client.get(f"orgs/{org}/teams/{slug}")
            if resp and resp.status_code == 200:
                existing = resp.json()
                existing_parent_id = existing.get("parent", {}).get("id") if existing.get("parent") else None

                # Check for mismatch: parent team changed
                if desired_parent_id != existing_parent_id:
                    log.info("Team '%s' exists but parent mismatch (current=%s, desired=%s), updating",
                             slug, existing_parent_id, desired_parent_id)
                    update_payload: dict[str, Any] = {
                        "name": slug,
                        "description": f"Migrated from GitLab group: {gm.gitlab_group_path}",
                        "privacy": "closed",
                    }
                    if desired_parent_id:
                        update_payload["parent_team_id"] = desired_parent_id
                    patch_resp = self.client.patch(f"orgs/{org}/teams/{slug}", json=update_payload)
                    if patch_resp is None and self.client.dry_run:
                        self.teams_updated.append(slug)
                    elif patch_resp and patch_resp.status_code == 200:
                        log.info("Updated team: %s", slug)
                        self.teams_updated.append(slug)
                    else:
                        status = patch_resp.status_code if patch_resp else "N/A"
                        log.error("Failed to update team '%s': %s", slug, status)
                else:
                    log.info("Team '%s' already exists with correct config, skipping", slug)
                    self.teams_skipped.append(slug)
                continue

            # Create team
            payload: dict[str, Any] = {
                "name": slug,
                "description": f"Migrated from GitLab group: {gm.gitlab_group_path}",
                "privacy": "closed",
            }
            if desired_parent_id:
                payload["parent_team_id"] = desired_parent_id

            resp = self.client.post(f"orgs/{org}/teams", json=payload)
            if resp is None and self.client.dry_run:
                self.teams_created.append(slug)
            elif resp and resp.status_code in (201, 200):
                log.info("Created team: %s", slug)
                self.teams_created.append(slug)
            else:
                status = resp.status_code if resp else "N/A"
                body = resp.text if resp else ""
                log.error("Failed to create team '%s': %s %s", slug, status, body)

        log.info("Teams created: %d, updated: %d, skipped (identical): %d",
                 len(self.teams_created), len(self.teams_updated), len(self.teams_skipped))

    # ------------------------------------------------------------------
    # Team memberships
    # ------------------------------------------------------------------

    def add_team_members(self) -> None:
        """Add users to GitHub teams based on effective group permissions."""
        log.info("Adding users to GitHub teams...")

        for perm in self.group_perms:
            gitlab_username = str(perm.get("Username", ""))
            group_path = str(perm.get("Group Path", ""))
            github_role_name = str(perm.get("GitHub Role", "Read"))

            # Resolve user mapping
            um = self.user_map.get(gitlab_username)
            if not um:
                continue  # User not mapped

            # Resolve group mapping
            gm = self.group_map.get(group_path)
            if not gm:
                continue  # Group not mapped

            org = gm.github_org or self.org
            team_slug = gm.github_team_slug
            team_role = ROLE_TO_TEAM_ROLE.get(github_role_name, "member")
            label = f"{um.github_username} → {team_slug} ({team_role})"

            # Check current membership
            check_resp = self.client.get(
                f"orgs/{org}/teams/{team_slug}/memberships/{um.github_username}"
            )
            if check_resp and check_resp.status_code == 200:
                current_data = check_resp.json()
                current_role = current_data.get("role", "")
                if current_role == team_role:
                    log.debug("Member '%s' already in team '%s' with role '%s', skipping",
                              um.github_username, team_slug, team_role)
                    self.members_skipped.append(label)
                    continue
                else:
                    log.info("Member '%s' in team '%s' has role '%s', updating to '%s'",
                             um.github_username, team_slug, current_role, team_role)

            # Add or update membership
            resp = self.client.put(
                f"orgs/{org}/teams/{team_slug}/memberships/{um.github_username}",
                json={"role": team_role},
            )
            if resp is None and self.client.dry_run:
                self.members_added.append(label)
            elif resp and resp.status_code in (200, 201):
                # Determine if this was an update or new addition
                if check_resp and check_resp.status_code == 200:
                    self.members_updated.append(label)
                else:
                    self.members_added.append(label)
            else:
                self.members_failed.append(label)
                log.warning("Failed to add %s to team %s", um.github_username, team_slug)

        log.info("Team members — added: %d, updated: %d, skipped (identical): %d, failed: %d",
                 len(self.members_added), len(self.members_updated),
                 len(self.members_skipped), len(self.members_failed))

    # ------------------------------------------------------------------
    # Repository permissions
    # ------------------------------------------------------------------

    def set_repo_permissions(self) -> None:
        """Set team permissions on repositories based on effective project permissions."""
        log.info("Setting repository permissions...")

        # Build: for each (project, group) → highest role needed
        # We assign team-level repo permissions (not individual user permissions)
        team_repo_perms: dict[tuple[str, str, str], str] = {}  # (org, team_slug, repo) → permission

        for perm in self.project_perms:
            gitlab_username = str(perm.get("Username", ""))
            project_path = str(perm.get("Project Path", ""))
            github_role_name = str(perm.get("GitHub Role", "Read"))
            inherited_from = str(perm.get("Inherited From", ""))

            # Resolve project mapping
            pm = self.project_map.get(project_path)
            if not pm:
                continue

            org = pm.github_org or self.org
            repo = pm.github_repo_name
            permission = ROLE_TO_REPO_PERMISSION.get(github_role_name, "pull")

            # If permission came from a group, assign at team level
            if inherited_from and inherited_from != "direct":
                # Find group mapping for the inherited source
                source_path = inherited_from.replace("shared:", "")
                gm = self.group_map.get(source_path)
                if gm:
                    key = (org, gm.github_team_slug, repo)
                    current = team_repo_perms.get(key)
                    if current is None or GITHUB_REPO_PERMISSIONS.index(permission) > GITHUB_REPO_PERMISSIONS.index(current):
                        team_repo_perms[key] = permission
                    continue

            # Direct permission → add user as collaborator (with idempotent check)
            um = self.user_map.get(gitlab_username)
            if um:
                label = f"{um.github_username} → {org}/{repo} ({permission})"

                # Check current collaborator permission
                check_resp = self.client.get(
                    f"repos/{org}/{repo}/collaborators/{um.github_username}/permission"
                )
                if check_resp and check_resp.status_code == 200:
                    current_perm = check_resp.json().get("permission", "")
                    # GitHub returns: admin, maintain, write(push), triage, read(pull)
                    # Normalize: GitHub uses "write" but API accepts "push", uses "read" but accepts "pull"
                    perm_normalize = {"write": "push", "read": "pull"}
                    current_normalized = perm_normalize.get(current_perm, current_perm)
                    if current_normalized == permission:
                        log.debug("Collaborator '%s' on '%s/%s' already has '%s', skipping",
                                  um.github_username, org, repo, permission)
                        self.repo_perms_skipped.append(label)
                        continue
                    else:
                        log.info("Collaborator '%s' on '%s/%s' has '%s', updating to '%s'",
                                 um.github_username, org, repo, current_normalized, permission)

                resp = self.client.put(
                    f"repos/{org}/{repo}/collaborators/{um.github_username}",
                    json={"permission": permission},
                )
                if resp is None and self.client.dry_run:
                    self.repo_perms_set.append(label)
                elif resp and resp.status_code in (200, 201, 204):
                    if check_resp and check_resp.status_code == 200:
                        self.repo_perms_updated.append(label)
                    else:
                        self.repo_perms_set.append(label)
                else:
                    self.repo_perms_failed.append(label)

        # Apply team-level repo permissions (with idempotent check)
        for (org, team_slug, repo), permission in team_repo_perms.items():
            label = f"team:{team_slug} → {org}/{repo} ({permission})"

            # Check current team permission on repo
            # Use special media type to get permissions in the response
            check_resp = self.client.get(
                f"orgs/{org}/teams/{team_slug}/repos/{org}/{repo}",
                headers={"Accept": "application/vnd.github.v3.repository+json"},
            )
            if check_resp and check_resp.status_code == 200:
                try:
                    resp_data = check_resp.json()
                    # Try role_name first (simpler), then fall back to permissions booleans
                    role_name = resp_data.get("role_name", "")
                    if role_name:
                        # role_name is: admin, maintain, write, triage, read
                        perm_normalize = {"write": "push", "read": "pull"}
                        current_level = perm_normalize.get(role_name, role_name)
                    else:
                        current_perms = resp_data.get("permissions", {})
                        current_level = "pull"
                        for lvl in GITHUB_REPO_PERMISSIONS:
                            if current_perms.get(lvl, False):
                                current_level = lvl
                    if current_level == permission:
                        log.debug("Team '%s' on '%s/%s' already has '%s', skipping",
                                  team_slug, org, repo, permission)
                        self.repo_perms_skipped.append(label)
                        continue
                    else:
                        log.info("Team '%s' on '%s/%s' has '%s', updating to '%s'",
                                 team_slug, org, repo, current_level, permission)
                except (ValueError, KeyError):
                    pass  # Can't parse response, proceed with PUT
            elif check_resp and check_resp.status_code == 204:
                # 204 means team has access but no body returned (old API behavior)
                # Can't determine current level — treat as needs-update to ensure correct perm
                log.debug("Team '%s' on '%s/%s' has access (204), verifying permission level",
                          team_slug, org, repo)

            resp = self.client.put(
                f"orgs/{org}/teams/{team_slug}/repos/{org}/{repo}",
                json={"permission": permission},
            )
            if resp is None and self.client.dry_run:
                self.repo_perms_set.append(label)
            elif resp and resp.status_code in (200, 201, 204):
                if check_resp and check_resp.status_code in (200, 204):
                    self.repo_perms_updated.append(label)
                else:
                    self.repo_perms_set.append(label)
            else:
                self.repo_perms_failed.append(label)

        log.info("Repo permissions — set: %d, updated: %d, skipped (identical): %d, failed: %d",
                 len(self.repo_perms_set), len(self.repo_perms_updated),
                 len(self.repo_perms_skipped), len(self.repo_perms_failed))

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------

    def print_summary(self) -> None:
        separator = "=" * 60
        print(f"\n{separator}")
        print("  GitHub Permission Migration Summary")
        print(separator)
        print(f"  Org members existing:  {len(self.org_members_existing):>6}")
        print(f"  Org members invited:   {len(self.org_members_invited):>6}")
        print(f"  Org members failed:    {len(self.org_members_failed):>6}")
        print(f"  Teams created:         {len(self.teams_created):>6}")
        print(f"  Teams updated:         {len(self.teams_updated):>6}")
        print(f"  Teams skipped:         {len(self.teams_skipped):>6}")
        print(f"  Members added:         {len(self.members_added):>6}")
        print(f"  Members updated:       {len(self.members_updated):>6}")
        print(f"  Members skipped:       {len(self.members_skipped):>6}")
        print(f"  Members failed:        {len(self.members_failed):>6}")
        print(f"  Repo perms set:        {len(self.repo_perms_set):>6}")
        print(f"  Repo perms updated:    {len(self.repo_perms_updated):>6}")
        print(f"  Repo perms skipped:    {len(self.repo_perms_skipped):>6}")
        print(f"  Repo perms failed:     {len(self.repo_perms_failed):>6}")
        print(separator)

        if self.org_members_failed:
            print("\n  Failed org invitations:")
            for item in self.org_members_failed[:20]:
                print(f"    - {item}")

        if self.teams_updated:
            print("\n  Updated teams (mismatch fixed):")
            for item in self.teams_updated[:20]:
                print(f"    - {item}")

        if self.members_updated:
            print("\n  Updated members (role changed):")
            for item in self.members_updated[:20]:
                print(f"    - {item}")

        if self.repo_perms_updated:
            print("\n  Updated repo permissions (mismatch fixed):")
            for item in self.repo_perms_updated[:20]:
                print(f"    - {item}")

        if self.members_failed:
            print("\n  Failed member additions:")
            for item in self.members_failed[:20]:
                print(f"    - {item}")

        if self.repo_perms_failed:
            print("\n  Failed repo permissions:")
            for item in self.repo_perms_failed[:20]:
                print(f"    - {item}")
        print()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="GitLab-to-GitHub Permission Migration Execution Tool",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --github-org my-org --github-token ghp_xxx --mappings-dir .
  %(prog)s --github-org my-org --github-token ghp_xxx --mappings-dir . --dry-run
  %(prog)s --github-org my-org --github-token ghp_xxx --mappings-dir . --skip-teams

Workflow:
  1. Run users_permissions_inventory.py to generate inventory + mapping CSVs
  2. Fill in GitHub columns in the mapping CSVs
  3. Run this script with --dry-run first to validate
  4. Run without --dry-run to execute migration
""",
    )
    parser.add_argument("--github-org", required=True,
                        help="Target GitHub organization")
    parser.add_argument("--github-token",
                        default=os.environ.get("GITHUB_TOKEN", ""),
                        help="GitHub PAT with admin:org, repo scopes (or set GITHUB_TOKEN)")
    parser.add_argument("--mappings-dir", required=True,
                        help="Directory containing mapping CSV files")
    parser.add_argument("--inventory",
                        default="GitLab_UsersPermissions_Inventory.xlsx",
                        help="Path to inventory Excel (default: in mappings-dir)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Simulate all actions without making changes")
    parser.add_argument("--skip-org-invite", action="store_true",
                        help="Skip org membership check/invite step")
    parser.add_argument("--skip-teams", action="store_true",
                        help="Skip team creation step")
    parser.add_argument("--skip-members", action="store_true",
                        help="Skip team member addition step")
    parser.add_argument("--skip-repos", action="store_true",
                        help="Skip repository permission step")
    parser.add_argument("--debug", action="store_true",
                        help="Enable debug logging")
    parser.add_argument("--version", action="version", version=f"%(prog)s {VERSION}")
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if not args.github_token:
        print("ERROR: GitHub token required. Use --github-token or set GITHUB_TOKEN env var.", file=sys.stderr)
        sys.exit(1)

    mappings_dir = Path(args.mappings_dir).resolve()
    script_dir = Path(__file__).resolve().parent
    log_file = script_dir / DEFAULT_LOG_FILENAME

    setup_logging(log_file, args.debug)
    log.info("GitLab-to-GitHub Permission Migration v%s", VERSION)
    log.info("Target org: %s | Dry-run: %s", args.github_org, args.dry_run)

    # Load mapping files
    user_map = load_user_mapping(mappings_dir / "gitlab_to_github_user_mapping.csv")
    group_map = load_group_mapping(mappings_dir / "gitlab_to_github_group_mapping.csv")
    project_map = load_project_mapping(mappings_dir / "gitlab_to_github_project_mapping.csv")

    if not user_map:
        log.warning("No user mappings loaded — fill in 'github_username' column in the CSV")
    if not group_map:
        log.warning("No group mappings loaded — fill in 'github_team_slug' column in the CSV")

    # Load effective permissions from Excel
    inventory_path = mappings_dir / args.inventory
    if not inventory_path.exists():
        inventory_path = script_dir / args.inventory
    group_perms, project_perms = load_effective_permissions(inventory_path)

    # Initialize client and migrator
    client = GitHubClient(args.github_token, dry_run=args.dry_run)
    migrator = PermissionMigrator(
        client=client,
        org=args.github_org,
        user_map=user_map,
        group_map=group_map,
        project_map=project_map,
        group_perms=group_perms,
        project_perms=project_perms,
    )

    # Execute migration steps
    start_time = time.time()

    if not args.skip_org_invite:
        migrator.ensure_org_membership()

    if not args.skip_teams:
        migrator.create_teams()

    if not args.skip_members:
        migrator.add_team_members()

    if not args.skip_repos:
        migrator.set_repo_permissions()

    migrator.print_summary()

    elapsed = time.time() - start_time
    mode = "DRY-RUN" if args.dry_run else "LIVE"
    log.info("[%s] Migration completed in %.1f seconds", mode, elapsed)
    print(f"  [{mode}] Completed in {elapsed:.1f}s")


if __name__ == "__main__":
    main()
